<?php
/**
 * Separation Degrees Media
 *
 * Collection Rendering Widget
 *
 * @category  SDM
 * @package   SDM_RenderCollection
 * @author    Separation Degrees Media <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees Media (http://www.separationdegrees.com)
 */
?>
<?php
$_productCollection = $this->getCollection();
$_collectionSize = is_array($_productCollection) ? count($_productCollection) : $_productCollection->getSize();
$_pageSize = is_array($_productCollection) ? count($_productCollection) : $_productCollection->count();
$_columnCount = 4;
?>
<?php if($_collectionSize): ?>
<div class="render-collection product-listing category-products">
    <p class="result-count"><?php echo $this->__('%s Results', $_collectionSize) ?></p>
    <?php echo $this->getToolbarHtml() ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++ === 0): ?>
        <ul class="products-grid" id="<?php echo $this->getCarouselId() ?>">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 300; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <ul class="add-to-links">
                        <?php if($this->helper('sendfriend')->isEnabled()) :?>
                            <li class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email') ?></a></li>
                        <?php endif;?>
                            <!-- <li class="download-pdf">
                                <a href='<?php echo $_product->getInstructionFile() ?>' class='instructions-link'>
                                    <?php echo $this->__('Download PDF') ?>
                                </a>
                            </li> -->
                    </ul>

                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>

                    <div class="sku"><?php echo Mage::helper('sdm_catalog')->getSkuLabel($_product) . $_product->getSku(); ?></div>

                    <a href='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $_product->getInstructionFile() ?>' class='instructions-button'>
                        <?php echo $this->__('Download Instructions') ?>
                    </a>
                </div>
            </li>
        <?php if ($i == $_pageSize): ?>
        </ul>
        <?php endif ?>
    <?php endforeach ?>
    <?php echo $this->getToolbarHtml() ?>
</div>
<?php else: ?>
    <p><?php echo $this->__('No instructions found.') ?></p>
<?php endif; ?>

