<?php
/**
 * Separation Degrees Media
 *
 * Magento catalog customizations
 *
 * @category  SDM
 * @package   SDM_Catalog
 * @author    Separation Degrees Media <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees Media (http://www.separationdegrees.com)
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <div class="pager">
        <?php echo $this->getPagerHtml() ?>
    </div>
</div>
<?php endif ?>
