<?php
/**
 * Separation Degrees One
 *
 * @category  design
 * @package   sdm_ellison
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<?php
/**
 * @var $this Mage_Adminhtml_Block_System_Currency
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-system-currency"><?php echo $this->getHeader() ?> (only 1:1 rates are allowed)</h3></td>
            <td class="form-buttons">
                <form action="<?php echo $this->getImportFormAction() ?>" method="post">
                    <?php echo $this->getBlockHtml('formkey')?>
                    <?php echo $this->getServicesHtml() ?>
                    <?php echo $this->getImportButtonHtml() ?>
                </form>
                <?php echo $this->getResetButtonHtml() ?>
                <?php echo $this->getSaveButtonHtml() ?>
            </td>
        </tr>
    </table>
</div>
<?php echo $this->getRatesMatrixHtml() ?>