<?php
/**
 * Separation Degrees One
 *
 * Lyris Newsletter Management
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Lyris
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

/**
 * @var SDM_Lyris_Block_Account $this
 */

$_submitText = $this->__($this->isEditMode() ? 'Click to update my Profile' : 'Sign-up to the Newsletter Now!');
$_interests = array(
    'Ellison Retailers',
    'Sizzix Retailers',
    'Sizzix Retailers in Spanish',
    'eClips',
    'Quilting',
    'Tim Holtz'
);
natcasesort($_interests);
?>
<form id="newsletter-signup" method="post" action="<?php echo $this->getEditFormAction() ?>">
    <?php if ($this->isEditMode()): ?>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Update my newsletter preferences') ?></h1>
    </div>
    <p><?php echo $this->__('Edit here to update your email preferences.') ?></p>
    <input type="hidden" name="edit" value="1" />
    <?php else: ?>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Sign up for the Ellison/Sizzix Retailers Newsletter?') ?></h1>
    </div>
    <p><?php echo $this->__('To become a subscriber to our %s, simply fill out the information below.', $this->getNewsletterName()) ?></p>
    <p><?php echo $this->__('When you sign up for the Ellison/Sizzix Retailers Newsletter, you will be connected to our latest products, special offers, inspiring ideas, designer details, helpful videos and much more! It’s also an easy way to access our blog and social media sites.') ?></p>
    <?php endif ?>
    <div class="fieldset">
        <ul class="form-list">
            <li>
                <label for="email" class="required"><em>*</em> <?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <?php if ($this->isEditMode()): ?>
                    <input type="hidden" name="email" value="<?php echo $this->getValue('email') ?>" />
                    <p><?php echo $this->getValue('email') ?>
                    <?php else: ?>
                    <input type="text" name="email" id="email" value="<?php echo $this->getValue('email') ?>" class="input-text required-entry validate-email" />
                    <?php endif ?>
                </div>
            </li>
            <li>
                <label for="name_first" class="required"><em>*</em> <?php echo $this->__('First Name') ?></label>
                <div class="input-box">
                    <input type="text" name="lyris_1" id="name_first" value="<?php echo $this->getValue('lyris_1') ?>" class="input-text required-entry" />
                </div>
            </li>
            <li>
                <label for="country" class="required"><em>*</em> <?php echo $this->__('Country') ?></label>
                <div class="input-box">
                    <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id') ?: 'US') ?>
                </div>
            </li>
            <li>
                <label for="address"><?php echo $this->__('Address') ?></label>
                <div class="input-box">
                    <input type="text" name="lyris_4" id="address" value="<?php echo $this->getValue('lyris_4') ?>" class="input-text" />
                </div>
            </li>
            <li>
                <label for="city"><?php echo $this->__('City') ?></label>
                <div class="input-box">
                    <input type="text" name="lyris_5" id="city" value="<?php echo $this->getValue('lyris_5') ?>" class="input-text" />
                </div>
            </li>
            <li>
                <label for="region_id" class="required"><em>*</em> <?php echo $this->__('State/Province') ?></label>
                <div class="input-box">
                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;" class="validate-select">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                   <input type="text" id="region" name="region" title="<?php echo $this->__('State/Province') ?>" class="input-text required-entry" style="display:none;" />
               </div>
            </li>
            <li>
                <label for="zip"><?php echo $this->__('Zip/Postal code') ?></label>
                <div class="input-box">
                    <input type="text" name="lyris_7" id="zip" value="<?php echo $this->getValue('lyris_7') ?>" class="input-text" />
                </div>
            </li>
            <li class="interest">
                <label><?php echo $this->__('Areas of interest') ?></label>
                <div class="input-box">
                    <?php foreach ($_interests as $_id => $_label): ?>
                    <span class="field">
                        <input type="checkbox" name="lyris_35811[]" id="interest_<?php echo $_id ?>" value="<?php echo $this->quoteEscape($_label) ?>"<?php echo (is_array($this->getValue('lyris_35811')) ? in_array($_label, $this->getValue('lyris_35811')) : $_label == $this->getValue('lyris_35811')) ? ' checked="checked"' : '' ?> />
                        <label for="interest_<?php echo $_id ?>"><?php echo $_label ?></label>
                    </span>
                    <?php endforeach ?>
                </div>
            </li>
            <?php if ($this->isEditMode()): ?>
            <input type="hidden" name="lyris_35811_original" value="<?php echo is_array($this->getValue('lyris_35811')) ? implode('||', $this->getValue('lyris_35811')) : $this->getValue('lyris_35811') ?>" />
            <?php endif ?>
        </ul>        
        <div class="buttons-set">
            <button type="button" title="<?php echo $_submitText ?>" onclick="newsletterSignup.submit()" class="button"><span><span><?php echo $_submitText ?></span></span></button>
        </div>
    </div>
    <div style="clear: both"></div>
</form>
<br />
<h3 style="clear: both;"><?php echo $this->__('To ensure delivery of The Sizzix/Ellison Retailer Newsletter...') ?></h3>
<p><?php echo $this->__('To ensure that your Sizzix/Ellison Retailer newsletter is delivered to your inbox, and not treated as spam, please add <a href="mailto:ellison_retail_news@marketing.ellison.com">ellison_retail_news@marketing.ellison.com</a> to your email address book as soon as possible. This will prevent any deliveries to your Bulk or Junk Mail folders.') ?></p>

<h3><?php echo $this->__('To unsubscribe to The Sizzix/Ellison Retailer Newsletter...') ?></h3>
<p><?php echo $this->__('To remove your subscription to the Ellison Connection Newsletter, please follow the unsubscribe link in your Sizzix/Ellison Retailer newsletter email.') ?></p>

<script type="text/javascript">
//<![CDATA[
    <?php if ($this->getValue('region_id')): ?>
    $('region_id').setAttribute('defaultValue', "<?php echo $this->getValue('region_id') ?>");
    <?php endif ?>
    <?php if ($this->getValue('country_id')): ?>
    $('country').setAttribute('defaultValue', "<?php echo $this->getValue('country_id') ?>");
    <?php endif ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    Validation.add('validate-one-required-by-name-placeholder', 'Please select one of the options.', function (v, elm) {
        var inputs = $$('input[name="' + elm.name.replace(/([\\"])/g, '\\$1').replace('\-placeholder', '') + '"]');
        var error = 1;
        for(var i=0;i<inputs.length;i++) {
            if ((inputs[i].type == 'checkbox' || inputs[i].type == 'radio') && inputs[i].checked == true) {
                error = 0;
            }
            if (Validation.isOnChange && (inputs[i].type == 'checkbox' || inputs[i].type == 'radio')) {
                Validation.reset(inputs[i]);
            }
        }
        return error == 0;
    });
    var newsletterSignup = new VarienForm('newsletter-signup');
    var newsletterLookup = new VarienForm('newsletter-lookup');
//]]>
</script>