<?php
$_address = $this->getShippingAddress(Mage::registry('shippingPost'));
$_streets = explode("\n", $_address->getStreet());
$_addressSelect = $this->getAddressesHtmlSelect('shipping');
?>
<h2><?php echo $this->__('Shipping Address') ?></h2>

<?php if (!empty($_addressSelect)): ?>
<div id='saved-quote-select-address'>
    <label for='".$type."-address-select'>
        <?php echo $this->__("Use Saved Address?") ?>
    </label>
    <div class="clear"></div>
    <?php echo $_addressSelect ?>
    <div class='message'>
        <?php echo $this->__("Select an address from your address book, or enter a new address below.<br>Only addresses matching the state, zip, and country used for your shipping estimate are available."); ?>
    </div>
</div>
<div class="clear"></div>
<?php endif; ?>

<?php echo $this->getBlockHtml('formkey'); ?>
<ul class="form-list">
    <li id="shipping-new-address-form" class="scaffold-form">
        <div class="fieldset">
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <input type="hidden" name="shipping[address_id]" value="<?php echo $_address->getId() ?>" id="shipping:address_id" />
            <ul>
                <li class="fields">
                    <div class="field name-firstname">
                        <label for="shipping:firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
                        <div class="input-box">
                            <input id="shipping:firstname" name="shipping[firstname]" value="<?php echo $this->escapeHtml($_address->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" maxlength="255" class="input-text required-entry" type="text">
                        </div>
                    </div>
                    <div class="field name-lastname">
                        <label for="shipping:lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
                        <div class="input-box">
                            <input id="shipping:lastname" name="shipping[lastname]" value="<?php echo $this->escapeHtml($_address->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" maxlength="255" class="input-text required-entry" type="text">
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="fields">
                        <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($_address->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                </li>
                <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($_streets[0]) ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
                <li class="wide">
                    <label for="shipping:street2" class=""><?php echo $this->__('Address 2') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address 2') ?>" name="shipping[street][]" id="shipping:street2" value="<?php echo (isset($_streets[1])) ? $this->escapeHtml($_streets[1]) : '' ?>" class="input-text" />
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($_address->getCity()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                        </div>
                    </div>
                    <div class="field disabled-field">
                        <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('State/Province') ?>" name="shipping[region]" value="<?php echo $this->escapeHtml($_address->getRegion()) ?>" class="input-text" id="shipping:region" readonly="readonly" />
                            <input type="hidden" name="shipping[region_id]" value="<?php echo $this->escapeHtml($_address->getRegionId()) ?>" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field disabled-field">
                        <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($_address->getPostcode()) ?>" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" readonly="readonly" />
                        </div>
                    </div>
                    <div class="field disabled-field">
                        <label for="shipping:country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php //echo $this->getCountryHtmlSelect('shipping') ?>
                            <input type="text" title="<?php echo $this->__('Country') ?>" name="shipping[country]" value="<?php echo $this->escapeHtml($this->getCountyNameById($_address->getCountryId())) ?>" class="input-text" id="shipping:country" readonly="readonly" />
                        </div>
                        <input type="hidden" name="shipping[country_id]" value="<?php echo $_address->getCountryId() ?>" />
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="tel" name="shipping[telephone]" value="<?php echo $this->escapeHtml($_address->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="tel" name="shipping[fax]" value="<?php echo $this->escapeHtml($_address->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" />
                        </div>
                    </div>
                </li>
                <li class="control">
                    <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save in address book')) ?>" id="shipping:save_in_address_book" class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                </li>
            </ul>
        </div>
    </li>
</ul>
