<?php
/**
 * Separation Degrees Media
 *
 * Collection Rendering Widget
 *
 * @category  SDM
 * @package   SDM_RenderCollection
 * @author    Separation Degrees Media <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees Media (http://www.separationdegrees.com)
 */
?>
<?php
    $_productCollection = $this->getCollection();
    $_collectionSize = is_array($_productCollection) ? count($_productCollection) : $_productCollection->count();
    $_helper = $this->helper('catalog/output');
    $_saleLabelHelper = $this->helper('sdm_catalog/salelabel');
    $_columnCount = 5;
?>
<?php if($_collectionSize): ?>
<div class="render-collection product-carousel category-products">
    <ul class="products-grid products-grid--max-<?php echo $_columnCount ?>-col collection-carousel owl-carousel" id="<?php echo $this->getCarouselId() ?>">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php echo $_product->getTypeId() ?>">
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <?php $_imgSize = 210; ?>
                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            </a>
            <div class="product-info">
                <ul class="add-to-links">
                    <li class="view-details"><a title="<?php echo $this->__('Details') ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Details') ?></a></li>
                    <?php if($this->helper('sendfriend')->isEnabled()) :?>
                        <li class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email') ?></a></li>
                    <?php endif;?>
                    <!-- PlaceHolder Follow Product -->
                    <li class="follow-small">
                        <?php echo Mage::helper('followitem')->getProductFollowLinkHtml($_product) ?>
                    </li>
                    <!-- End Follow Product -->
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <li class="wishlist"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Wishlist') ?></a></li>
                    <?php endif; ?>
                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                    <?php endif; ?>
                </ul>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <div class="sku"><?php echo Mage::helper('sdm_catalog')->getSkuLabel($_product) . $_product->getSku(); ?></div>
                <?php
                // Provides extra blocks on which to hang some features for products in the list
                // Features providing UI elements targeting this block will display directly below the product name
                if ($this->getChild('name.after')) {
                    $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                    foreach ($_nameAfterChildren as $_nameAfterChildName) {
                        $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                        $_nameAfterChild->setProduct($_product);
                        echo $_nameAfterChild->toHtml();
                    }
                }
                ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php if ($_product->getButtonVisibleListing()): ?>
                    <div class="actions">
                        <?php if($_product->getButtonType() == 'text'): ?>
                            <p class="availability">
                                <span><?php echo $_product->getButtonValue() ?></span>
                            </p>
                        <?php elseif($_product->getButtonType() == 'add-to-cart'): ?>
                            <p class="action">
                                <button type="button" class="button btn-cart ajax-cart" data-ajax-url="<?php echo $this->getAddToCartUrl($_product) ?>">
                                    <span><span><?php echo $_product->getButtonValue() ?></span></span>
                                </button>
                            </p>
                        <?php else: ?>
                            <p class="action">
                                <a title="<?php echo $_product->getButtonValue() ?>" class="button" href="<?php echo $_product->getProductUrl() ?>">
                                    <span><span><?php echo $_product->getButtonValue() ?></span></span>
                                </a>
                            </p>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>
            <?php // Show sale label ?>
            <?php echo $_saleLabelHelper->getSaleLabelHtml($_product); ?>
        </li>
    <?php endforeach ?>
    </ul>
</div>
<?php endif; ?>
<script type='text/javascript'>
    <?php echo $this->getCarouselInit() ?>
</script>
