<?php

?>
<?php $saveQuoteUrl = $this->getSaveQuoteLink()?>
<?php if ($this->isPossibleOnepageCheckout()):?>
    <button type="button" title="<?php echo $this->__('Save Quote') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $saveQuoteUrl ?>';">
    <span>
        <span>
            <?php echo $this->__('Save Quote') ?>
        </span>
    </span>
    </button>
<?php endif?>
