<?php
/**
 * Separation Degrees One
 *
 * eCallite
 *
 * @category  SDM
 * @package   SDM_Ecallite
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<div class="ecallite-header">
    <h2><?php echo $this->__('Upgrade to the Full eCAL Software')?></h2>
    <p><?php echo $this->__('If you like the eCAL lite software, then you will love the eCAL software. The eCAL software will expand the limits of the eCAL lite program and add the following features to your craft arsenal:')?>
    </p>
    <ul>
        <li><?php echo $this->__('Import various file formats, including SVG')?></li>
        <li><?php echo $this->__('Auto tracing feature to automatically convert images (including jpg, bmp, gif, png) for cutting')?></li>
        <li><?php echo $this->__('Create rhinestone templates and Lattice shapes')?></li>
        <li><?php echo $this->__('Print-2-Cut feature that allows you to print out an image and have the eclips Machine cut around the printed image')?></li>
        <li><?php echo $this->__('Upgrade now and unlock all of the features that eCAL has to offer. To for more information or to purchase the full version of the eCal software, visit ')?><a href="http://craftedge.com/products/products_ecal.html"><?php echo $this->__('http://craftedge.com/products/products_ecal.html')?></a></li>
    </ul>
    <p class="note"><strong><?php echo $this->__('NOTE: ')?></strong><?php echo $this->__('Remember to check your email junk/spam folder, if your activation email doesnt show in your email inbox')?></p>
</div>