<?php
/**
 * Separation Degrees One
 *
 * eCallite
 *
 * @category  SDM
 * @package   SDM_Ecallite
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<div class="ecallite-header">
    <h2><?php echo $this->__('eCAL Lite Free Software Download')?></h2>
    <h3><?php echo $this->__('Thank you for purchasing the eclips2 machine.')?></h3>
    <p><?php echo $this->__('We are pleased that you have chosen the eclips2 to help bring to life all your many do-it-yourself (DIY) projects, including cardmaking, scrapbooking, invitations, party favors and other fun papercrafting and arts crafts projects. As a Sizzix eclips user, you are entitled to a FREE copy of eCAL lite software. With eCAL lite, you can create your own designs, weld shapes and fonts together, purchase new digital designs from the eshape Store, size and skew designs to your liking and much more.')?>
    </p>
    <p><?php echo $this->__('When you opened the box to your brand new eclips2, you may have noticed a card with an eCAL lite Authorization number. Please find this card and locate your Authorization number. After you submit your name, email address and eCAL lite Authorization Code below, please check your Inbox for an email from CraftEdge containing your eCAL lite software activation link and serial number. If you do not see this email, check your Junk Folder. Click the link in your email to download the eCAL lite Software. If you experience problems with the provided link, copy the link directly into your browser. Open the eCAL lite Software installer and follow the on-screen instructions to install the application on your computer. Open the eCAL lite Software installer and follow the on-screen instructions to install the application on your computer. When the activation prompt appears, enter the eCAL lite serial number that was provided in your email.')?>
    </p>
</div>