<?php
/**
 * Separation Degrees One
 *
 * eCallite
 *
 * @category  SDM
 * @package   SDM_Ecallite
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<div class="ecallite-preheader">
    <img class="" alt="eCal Lite Header Image"  src="<?php echo $this->getSkinUrl('sdm/ecallite/images/eCalLite.png') ?>" />
</div>