<?php
/**
 * Separation Degrees One
 *
 * Valutec Giftcard Integration
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Valutec
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
/**
 * @var SDM_Valutec_Block_Sales_Order_Giftcards $this
 */

$_order  = $this->getOrder();
$_card   = $this->getGiftCards();
?>
<?php if ($_card):?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo $this->__('Gift Card (%s)', $_card['number']); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_order->getSdmValutecGiftcardAmount()) ?></td>
</tr>
<?php endif?>
