<?php
/**
 * Separation Degrees One
 *
 * Handles designer page and designer article rendering
 *
 * @category  SDM
 * @package   SDM_Designer
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

$_designer = Mage::helper('sdm_designer')->getCurrentDesigner();

?>
<div class="designer-top">
	<ul class="top-links">
		<li class='follow-top'>
			<!-- PlaceHolder Follow Product -->
		    <?php echo Mage::helper('followitem')->getTaxonomyFollowLinkHtml($_designer, 'Designer') ?>
            <div class="emailtoafriend">
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_designer) ?>" class="link-email-friend" title="<?php echo $this->__('Email to a Friend') ?>"><?php echo $this->__('Email to a Friend') ?></a>
            </div>
		    <!-- End Follow Product -->
		</li>
	</ul>
    <div class="page-title title-buttons">
        <h1><?php echo $_designer->getName() ?></h1>
    </div>
    <div class="social">
		<!-- Go to www.addthis.com/dashboard to customize your tools -->
	    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-550083b37b032f8f" async="async"></script>
	    <!-- Go to www.addthis.com/dashboard to customize your tools -->
	    <div class="addthis_native_toolbox"></div>
    </div>
</div>
<div class="clear"></div>
<div class="designer-content">
	<?php echo $this->getChildHtml('designer_page_tabs') ?>
</div>
