<?php
/**
 * Separation Degrees Media
 *
 * Store switcher for UK
 *
 * @category  SDM
 * @package   SDM_StoreSwitcher
 * @author    Separation Degrees Media <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees Media (http://www.separationdegrees.com)
 */
?>

<a href="<?php echo $this->getSwitcherUrl() ?>" class="<?php echo $this->getClass() ?>">
	<?php echo $this->getSymbol() ?>
</a>
