<?php
/**
 * Separation Degrees Media
 *
 * Embed Youtube Videos and Playlists
 *
 * @category  SDM
 * @package   SDM_YoutubeFeed
 * @author    Separation Degrees Media <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees Media (http://www.separationdegrees.com)
 */

/**
 * @var SDM_YoutubeFeed_Block_Channel_View_List $this
 */
?>
<div class="channel-view-list">
    <h2><?php echo $this->__('Videos') ?></h2>
    <?php echo $this->getListHtml() ?>
</div>