<?php

$_quote = $this->getQuote();

?>
<?php $_mergedCells = 1; // Only need to display quoted price ?>
<div class="cart">
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Pre-Order') ?></h1>
    </div>

    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <form action="<?php echo $this->getUrl('savedquote/quote/save') ?>" method="post" id='saved-quote-form'>
        <?php echo $this->getBlockHtml('formkey'); ?>

        <input name="saved_quote_id" value="<?php echo $this->getSavedQuoteId() ?>" type="hidden">
        <table id="saved-quote-table" class="cart-table data-table">
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <col width="1" />
            <thead>
                <tr>
                    <th rowspan="<?php echo $_mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product') ?></span></th>
                    <th rowspan="<?php echo $_mergedCells; ?>">&nbsp;</th>
                    <th class="a-center cart-price-head" colspan="<?php echo $_mergedCells; ?>">
                        <span class="nobr"><?php echo $this->__('Price') ?></span>
                    </th>
                    <th rowspan="<?php echo $_mergedCells; ?>" class="a-center">
                        <?php echo $this->__('Qty') ?>
                    </th>
                    <th class="a-center cart-total-head" colspan="<?php echo $_mergedCells; ?>">
                        <?php echo $this->__('Subtotal') ?>
                    </th>
                    <th class="a-center" rowspan="<?php echo $_mergedCells; ?>">&nbsp;</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <!-- Option to go back to cart  -->
                    <td colspan="50" class="a-right cart-footer-actions">
                        <button type="button" title="<?php echo $this->__('Edit Cart') ?>" class="button2 btn-continue" onclick="setLocation('<?php echo $this->getShoppingCartUrl() ?>')"><span><span><?php echo $this->__('Edit Cart') ?></span></span></button>
                    </td>
                </tr>
            </tfoot>
            <tbody>
            <!-- List items -->
            <?php
            foreach($this->getItems() as $_item):
                // Mage::log(get_class($_item));
                echo $this->getSavedQuoteItemHtml($_item);
            endforeach
            ?>
            </tbody>
        </table>


        <!-- Totals block -->
        <div class="cart-totals-wrapper">
            <div class="cart-totals">
                <?php echo $this->getChildHtml('totals'); ?>
            </div>
            <input name="saved_quote_name" value="<?php echo $this->__('Pre-Order') ?>" type="hidden">
            <input type="submit" title="<?php echo $this->__('Place Quote') ?>" class="button btn-proceed-checkout btn-checkout" value="<?php echo $this->__('Place Pre-Order') ?>" />
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var savedQuoteForm = new VarienForm('saved-quote-form');
    //]]>
    jQuery(document).ready(function(){
        jQuery('#saved-quote-form').on('submit', function(){
            return savedQuoteForm.validator.validate();
        });
    });
    </script>
</div>
