<?php
/**
 * Separation Degrees One
 *
 * Checkout-related customization
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Checkout
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<?php
$_parentId = $this->getInfo()->getParentId();
$_type = SDM_Checkout_Helper_Data::PURCHASE_ORDER_PAYMENT_CODE;
$_upload = $this->getUpload($_parentId, $_type);
$filePath = str_replace('index.php/', '', Mage::getUrl() . $_upload->getPath());
$isErus = ($this->getOrder($_parentId)->getStore()->getCode() === SDM_Core_Helper_Data::STORE_CODE_ER) ? true : false;
$isEeus = ($this->getOrder($_parentId)->getStore()->getCode() === SDM_Core_Helper_Data::STORE_CODE_EE) ? true : false;

?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<p><?php echo Mage::helper('payment')->__('Purchase Order Number: %s', $this->escapeHtml($this->getInfo()->getPoNumber())) ?></p>
<?php if ($isErus || $isEeus): // Only display PO file for ERUS ?>
    <?php echo $this->__('PO File') ?>:
    <?php if ($_upload->getId()): ?>
        <?php $_fileExists = false ?>
        [<a href="<?php echo $filePath ?>" target="_blank"><?php echo $_upload->getLabel() ?></a>]
    <?php else: ?>
        <?php $_fileExists = true ?>
        [Login as customer to upload a file]
    <?php endif; ?>
<?php endif; ?>
