<?php
/**
 * Separation Degrees One
 *
 * Projects Content template
 *
 * @category  SDM
 * @package   SDM
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

$_product = $this->getProduct();
$_projectCollection = $_product->getAssociatedParentsHtml();
?>
<?php if (!empty($_projectCollection)): ?>
    <h2 class="related-title">
        <?php echo $this->__('Related ' . Mage::helper('sdm_catalog')->getProjectLabelFromProduct($_product) . 's') ?>
    </h2>
    <?php echo $_projectCollection ?>
<?php endif; ?>
