<?php
/**
 * Separation Degrees One
 *
 * Accessories
 *
 * @category  SDM
 * @package   SDM
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

$_accessoriesHtml = $this->getAccessoriesHtml(1);

?>
<?php if (!empty($_accessoriesHtml)): ?>
    <h2 class="related-title">
    	<?php echo $this->__('Related Accessories') ?>
    </h2>
    <?php echo $_accessoriesHtml; ?>
<?php endif;?>
