<?php
/**
 * Separation Degrees One
 *
 * Valutec Giftcard Integration
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Valutec
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

/**
 * @var SDM_Valutec_Block_Page_Html_Head_js $this
 */
?>
<script>
// <![CDATA[
var sdm_valutec_giftcard = new SDM_Valutec_Giftcard('<?php echo $this->getUrlApply() ?>', '<?php echo $this->getUrlBalance() ?>', '<?php echo $this->getUrlRemove() ?>');
// ]]>
</script>