<?php
/**
 * Separation Degrees One
 *
 * Lyris Newsletter Management
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Lyris
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

/**
 * @var SDM_Lyris_Block_Account $this
 */

$_submitText = $this->__($this->isEditMode() ? 'Click to update my Profile' : 'Join %s', $this->getNewsletterName());
$_machines = array(
    array(
        'value' => 'Big Shot',
        'label' => 'Big Shot&trade;',
    ),
    array(
        'value' => 'Big Shot Pro',
        'label' => 'Big Shot&trade; Pro',
    ),
    array(
        'value' => 'Big Shot Plus',
        'label' => 'Big Shot&trade; Plus',
    ),
    array(
        'value' => 'BIGKick',
        'label' => 'BIGKick&trade;',
    ),
    array(
        'value' => 'eclips',
        'label' => 'eClips&trade;',
    ),
    array(
        'value' => 'Sidekick',
        'label' => 'Sidekick&trade;',
    ),
    array(
        'value' => 'Texture Boutique',
        'label' => 'Texture Boutique&trade;',
    ),
    array(
        'value' => 'Vagabond',
        'label' => 'Vagabond&trade;',
    ),
    array(
        'value' => 'Vintaj BIGKick',
        'label' => 'Vintaj BIGKick&trade;',
    ),
    array(
        'value' => 'Other',
        'label' => 'Other',
    ),
);
$_interests = array(
    'Cardmaking',
    'Electronic Cutting',
    'Fashion',
    'Home Decor',
    'Jewelry',
    'Papercrafting',
    'Quilting & Applique',
    'Scrapbooking',
    'Party Planning',
    'Gift Giving',
    'Gift Wrapping'
);
natcasesort($_interests);
$thumbCollection = $this->getPreviousThumbnails();
?>
<form id="newsletter-signup" method="post" action="<?php echo $this->getEditFormAction() ?>">
    <input type="hidden" name="lyris_37658" value="Newsletter Signup Page" />
    <?php if ($this->isEditMode()): ?>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Update my newsletter preferences') ?></h1>
    </div>
    <p><?php echo $this->__('Edit here to update your email preferences.') ?></p>
    <input type="hidden" name="edit" value="1" />
    <?php else: ?>
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('Sign Up Now! %s', $this->getNewsletterName()) ?></h1>
    </div>
    <p><?php echo $this->__('When you sign up for the Sizzix Newsletter, you will be connected to our latest products, special offers, inspiring ideas, designer details, helpful videos and much more! It’s also an easy way to access our blog and social media sites.')?></p>
    <p><?php echo $this->__('Join us today by filling out the form below. Once you submit your information, you will receive an email to the address you provide, requesting that you confirm the details you’ve submitted. Simply click on the link in the email to finalize your registration and begin receiving the Scoop. As an added incentive, new subscribers will receive a coupon code for added savings. It’s our way of welcoming you to the Scoop!') ?></p>
    <?php endif ?>
    <div class="fieldset">
        <ul class="form-list">
            <li>
                <label for="email" class="required"><em>*</em> <?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <?php if ($this->isEditMode()): ?>
                    <input type="hidden" name="email" value="<?php echo $this->getValue('email') ?>" />
                    <p><?php echo $this->getValue('email') ?>
                    <?php else: ?>
                    <input type="text" name="email" id="email" value="<?php echo $this->getValue('email') ?>" class="input-text required-entry validate-email" />
                    <?php endif ?>
                </div>
            </li>
            <li>
                <label for="name_first" class="required"><em>*</em> <?php echo $this->__('First Name') ?></label>
                <div class="input-box">
                    <input type="text" name="lyris_1" id="name_first" value="<?php echo $this->getValue('lyris_1') ?>" class="input-text required-entry" />
                </div>
            </li>
            <li class="gender">
                <label class="required"><em>*</em> <?php echo $this->__('Gender') ?></label>
                <div class="input-box">
                    <?php foreach ($this->getGenders() as $_value => $_label): ?>
                    <span class="field">
                        <input type="radio" name="lyris_11" id="gender_<?php echo $_value ?>" value="<?php echo $_value ?>"<?php echo $this->getValue('lyris_11') === $_value ? ' checked="checked"' : '' ?> />
                        <label for="gender_<?php echo $_value ?>"><?php echo $_label ?></label>
                    </span>
                    <?php endforeach ?>
                </div>
                <input type="hidden" name="lyris_11-placeholder" class="validate-one-required-by-name-placeholder" />
            </li>
            <li>
                <label for="country" class="required"><em>*</em> <?php echo $this->__('Country') ?></label>
                <div class="input-box">
                    <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id') ?: 'US') ?>
                </div>
            </li>
            <li>
                <label for="region_id" class="required"><em>*</em> <?php echo $this->__('State/Province') ?></label>
                <div class="input-box">
                    <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" style="display:none;" class="validate-select">
                        <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                    </select>
                   <input type="text" id="region" name="region" title="<?php echo $this->__('State/Province') ?>" class="input-text required-entry" style="display:none;" />
               </div>
            </li>
            <li class="birthday">
                <label for="birth_month"><?php echo $this->__('Birthday') ?></label>
                <div class="input-box">
                    <select id="birth_month" name="lyris_37655" title="<?php echo $this->__('Birth Month') ?>">
                        <option value=""><?php echo $this->__('Month') ?></option>
                        <?php foreach ($this->getBirthMonths() as $_value => $_label): ?>
                        <option value="<?php echo $_value ?>"<?php echo $this->getValue('lyris_37655') == $_value ? ' selected="selected"' : '' ?>><?php echo $_label ?></option>
                        <?php endforeach ?>
                    </select>
                    <select id="birth_day" name="lyris_37656" title="<?php echo $this->__('Birth Day') ?>">
                        <option value=""><?php echo $this->__('Day') ?></option>
                        <?php foreach ($this->getBirthDays() as $_value): ?>
                        <option value="<?php echo $_value ?>"<?php echo $this->getValue('lyris_37656') == $_value ? ' selected="selected"' : '' ?>><?php echo $_value ?></option>
                        <?php endforeach ?>
                    </select>
                    <select id="birth_year" name="lyris_37802" title="<?php echo $this->__('Birth Year') ?>">
                        <option value=""><?php echo $this->__('Year') ?></option>
                        <?php foreach ($this->getBirthYears() as $_value): ?>
                        <option value="<?php echo $_value ?>"<?php echo $this->getValue('lyris_37802') == $_value ? ' selected="selected"' : '' ?>><?php echo $_value ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
            </li>
            <li class="machine">
                <label><?php echo $this->__('Which Sizzix&reg; Machines do you use?') ?></label>
                <div class="input-box">
                    <?php foreach ($_machines as $_id => $_value): ?>
                    <span class="field">
                        <input type="checkbox" name="lyris_37654[]" id="machine_<?php echo $_id ?>" value="<?php echo $_value['value'] ?>"<?php echo (is_array($this->getValue('lyris_37654')) ? in_array($_value['value'], $this->getValue('lyris_37654')) : $_value['value'] == $this->getValue('lyris_37654')) ? ' checked="checked"' : '' ?> />
                        <label for="machine_<?php echo $_id ?>"><?php echo $_value['label'] ?></label>
                    </span>
                    <?php endforeach ?>
                </div>
            </li>
            <?php if ($this->isEditMode()): ?>
            <input type="hidden" name="lyris_37654_original" value="<?php echo is_array($this->getValue('lyris_37654')) ? implode('||', $this->getValue('lyris_37654')) : $this->getValue('lyris_37654') ?>" />
            <?php endif ?>
            <li class="interest">
                <label><?php echo $this->__('Areas of interest') ?></label>
                <div class="input-box">
                    <?php foreach ($_interests as $_id => $_label): ?>
                    <span class="field">
                        <input type="checkbox" name="lyris_35424[]" id="interest_<?php echo $_id ?>" value="<?php echo $this->quoteEscape($_label) ?>"<?php echo (is_array($this->getValue('lyris_35424')) ? in_array($_label, $this->getValue('lyris_35424')) : $_label == $this->getValue('lyris_35424')) ? ' checked="checked"' : '' ?> />
                        <label for="interest_<?php echo $_id ?>"><?php echo $_label ?></label>
                    </span>
                    <?php endforeach ?>
                </div>
            </li>
            <?php if ($this->isEditMode()): ?>
            <input type="hidden" name="lyris_35424_original" value="<?php echo is_array($this->getValue('lyris_35424')) ? implode('||', $this->getValue('lyris_35424')) : $this->getValue('lyris_35424') ?>" />
            <?php endif ?>
        </ul>
        <div class="buttons-set">
            <button type="button" title="<?php echo $_submitText ?>" onclick="newsletterSignup.submit()" class="button"><span><span><?php echo $_submitText ?></span></span></button>
        </div>
    </div>
    <div class="fieldset">
        <?php foreach ($thumbCollection as $thumb) {

        }?>
        <ul id="thumb-image">
            <?php foreach ($thumbCollection as $thumb) :
                $thumbImage = $thumb->getImage();
                $thumbTitle = $thumb->getTitle();
            ?>
            <li>
                <?php if(!empty($thumbImage)):?>
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $thumbImage; ?>" alt="<?php echo $thumbTitle;?>"/>
                <?php endif?>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div style="clear: both"></div>
</form>
<br />
<h3 style="clear: both;"><?php echo $this->__('To ensure delivery of The Scoop...') ?></h3>
<p><?php echo $this->__('To ensure that your Sizzix.com Scoop newsletter is delivered to your inbox, and not treated as spam, please add <a href="mailto:sizzixscoop@marketing.sizzix.com">sizzixscoop@marketing.sizzix.com</a> to your email address book as soon as possible. This will prevent any deliveries to your Bulk or Junk Mail folders.') ?></p>

<h3><?php echo $this->__('To unsubscribe to The Scoop...') ?></h3>
<p><?php echo $this->__('To remove your subscription to the Sizzix.com Scoop, please follow the unsubscribe link in your Scoop newsletter email.') ?></p>

<script type="text/javascript">
//<![CDATA[
    <?php if ($this->getValue('region_id')): ?>
    $('region_id').setAttribute('defaultValue', "<?php echo $this->getValue('region_id') ?>");
    <?php endif ?>
    <?php if ($this->getValue('country_id')): ?>
    $('country').setAttribute('defaultValue', "<?php echo $this->getValue('country_id') ?>");
    <?php endif ?>
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>);
    Validation.add('validate-one-required-by-name-placeholder', 'Please select one of the options.', function (v, elm) {
        var inputs = $$('input[name="' + elm.name.replace(/([\\"])/g, '\\$1').replace('\-placeholder', '') + '"]');
        var error = 1;
        for(var i=0;i<inputs.length;i++) {
            if ((inputs[i].type == 'checkbox' || inputs[i].type == 'radio') && inputs[i].checked == true) {
                error = 0;
            }
            if (Validation.isOnChange && (inputs[i].type == 'checkbox' || inputs[i].type == 'radio')) {
                Validation.reset(inputs[i]);
            }
        }
        return error == 0;
    });
    var newsletterSignup = new VarienForm('newsletter-signup');
    var newsletterLookup = new VarienForm('newsletter-lookup');
//]]>
</script>