<?php
/**
 * Separation Degrees One
 *
 * Lyris Newsletter Management
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Lyris
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

/**
 * @var SDM_Lyris_Block_Account $this
 */

$_submitText =  $this->__('Unsubscribe');
?>
<form id="newsletter-unsubscribe" method="post" action="<?php echo $this->getEditFormAction() ?>">
    <input type="hidden" name="unsubscribe" value="1" />
    <div class="page-title title-buttons">
        <h1><?php echo $this->__('%s Unsubscription', $this->getNewsletterName()) ?></h1>
    </div>
    <div class="fieldset">
        <ul class="form-list">
            <li>
                <label for="email" class="required"><em>*</em> <?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" id="email" value="<?php echo $this->getValue('email') ?>" class="input-text required-entry validate-email" />
                </div>
            </li>
        </ul>
        <div class="buttons-set">
            <button type="button" title="<?php echo $_submitText ?>" onclick="newsletterUnsubscribe.submit()" class="button"><span><span><?php echo $_submitText ?></span></span></button>
        </div>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterUnsubscribe = new VarienForm('newsletter-unsubscribe');
//]]>
</script>
