<?php
/**
 * Separation Degrees One
 *
 * Valutec Giftcard Integration
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Valutec
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
/**
 * @var Mage_Adminhtml_Block_Sales_Order_Totals_Item $this
 */
$_source = $this->getSource();
$this->setPriceDataObject($_source);
$_amount     = (float) $_source->getSdmValutecGiftcardAmount();
$_baseAmount = (float) $_source->getBaseSdmValutecGiftcardAmount();
?>
<?php if ($_amount): ?>
    <?php $_card = $this->helper('sdm_valutec')->getGiftcard($_source); ?>
    <tr>
        <td class="label"><?php echo $this->__('Giftcard (%s)', $_card['number']) ?></td>
        <td>
            <?php echo $this->displayPrices(-$_baseAmount, -$_amount); ?>
        </td>
    </tr>
<?php endif; ?>