<?php if ($this->isPossibleOnepageCheckout() && $this->helper('sdm_preorder')->isQuotePreOrder()): ?>
<?php $_reviewQuoteUrl = $this->getReviewQuoteLink()?>
<button type="button" title="<?php echo $this->__('Pre-Order') ?>" class="button btn-proceed-checkout btn-checkout<?php if ($this->isDisabled()):?> no-checkout<?php endif; ?>"<?php if ($this->isDisabled()):?> disabled="disabled"<?php endif; ?> onclick="window.location='<?php echo $_reviewQuoteUrl ?>';">
<span>
    <span>
        <?php echo $this->__('Pre-Order') ?>
    </span>
</span>
</button>
<p><?php echo $this->__('There are items in the cart that are available for pre-order only. If you would like to place a pre-order please click "Pre-Order". For immediate shipping please remove/move Pre-order items from cart.') ?></p>
<?php endif?>
