<?php
/**
 * Separation Degrees One
 *
 * Ellison's AX ERP integration
 *
 * @category  SDM
 * @package   SDM_Ax
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
?>
<script type="text/javascript">
    //<![CDATA[
    function runProductUpdate() {
        new Ajax.Request('<?php echo $this->getAjaxActionUrl('updateProduct') ?>', {
            method: 'get',
            onSuccess: function(transport){
                var json = transport.responseText;
                responseObject = JSON.parse(json);

                if (responseObject.result){
                    alert(responseObject.message);
                }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>