<?php
/**
 * Empty cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
	<div class="page-title title-buttons">
		<h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
	</div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

	<p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
	<p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>

	<?php echo $this->getChildHtml('form_before') ?>
	<div></div>
</div>
