<?php
/**
 * Separation Degrees One
 *
 * Ellison and Sizzix Shipping Rules
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Shipping
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
/**
 * @var Mage_Adminhtml_Block_Sales_Order_Totals_Item $this
 */
$_source = $this->getSource()->getShippingAddress();
$_amount     = (float) $_source->getSdmShippingSurcharge();
$_baseAmount = (float) $_source->getBaseSdmShippingSurcharge();
?>
<?php if ($_amount): ?>
    <tr>
        <td class="label"><?php echo $this->__('Shipping &amp; Handling Surcharge') ?></td>
        <td>
            <?php echo $this->displayPrices($_baseAmount, $_amount); ?>
        </td>
    </tr>
<?php endif; ?>