<?php
/**
 * Separation Degrees One
 *
 * Ellison's Teachers' Planning Calendar
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Calendar
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

/**
 * @var SDM_Calendar_Block_Event_List $this
 */
$_processor = Mage::helper('cms')->getBlockTemplateProcessor();
$_calendar = $this->getCalendar();
$_events   = $this->getEvents();
echo $_processor->filter($_calendar->getDesc());
if ($_events):
?>
<div id="sdm-calendar-events-<?php echo $_calendar->getId() ?>" class='list-calendar'>
    <table>
        <thead>
            <tr>
                <th colspan="2"><?php echo $this->__('Event') ?></th>
                <th><?php echo $this->__('Location') ?></th>
                <th><?php echo $this->__('Event Dates') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($_events as $_event): ?>
            <tr>
                <td class="image">
                    <?php if ($_event['image']): ?>
                    <a href="<?php echo $this->getUrl('*/*/view', array('id' => $_event['id'])) ?>"><img src="<?php echo Mage::getBaseUrl('media') . DS . $_event['image'] ?>" /></a>
                    <?php endif ?>
                </td>
                <td class="title"><a href="<?php echo $this->getUrl('*/*/view', array('id' => $_event['id'])) ?>"><?php echo $_event['title'] ?></a></td>
                <td class="location">
                    <?php echo !empty($_event['location']) ? "<p>".$_event['location']."</p>" : "" ?>
                    <?php echo $_event['street'] ?></br>
                    <?php echo $_event['city'] ?>, <?php echo $_event['state'] ?> <?php echo $_event['zip'] ?></br>
                    <?php echo $_event['country'] ?>
                </td>
                <td class="dates">
                    <?php echo $this->getReadableDate($_event['start']) ?>
                    <?php if (isset($_event['end'])): ?>
                        - <?php echo $this->getReadableDate($_event['end']) ?>
                    <?php endif ?>
                </td>
                <td>
                    <a class="button" href="<?php echo $this->getUrl('*/*/view', array('id' => $_event['id'])) ?>"><?php echo $this->__('View Details') ?></a>
                    <a href="https://www.google.com/maps/search/<?php echo urlencode($_event['street'] . ', ' . $_event['zip'] . ', ' . $_event['country']) ?>" target="_blank" class="map"><i class="fa fa-map-marker"></i><?php echo $this->__(' Map Event') ?></a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php else: ?>
<p style="font-weight: bold; margin-top: 20px;"><?php echo $this->__('No upcoming events scheduled at this time. Please visit us later.') ?></p>
<?php endif ?>
