<?php
/**
 * Separation Degrees One
 *
 * Press release listing and article rendering 
 *
 * @category  SDM
 * @package   SDM_PressReleases
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

$_filters = $this->getFilters();
$_current = $this->getCurrentFilter();

?>
<?php if (!empty($_filters)): ?>
	<h3><?php echo $this->__('Filter By Date') ?>
	<?php if (!empty($_current)): ?>
	    <a href="<?php echo Mage::getUrl('pressreleases') ?>"><i class="fa fa-times"></i></a>
	<?php endif; ?>
	</h3>
	<ul class='news-filters'>
		<?php foreach($_filters as $_id => $_filter): ?>
			<li class='<?php echo $_filter['classes'] ?>'>
				<a href='<?php echo $_filter['url']; ?>'><?php echo $_filter['label']; ?></a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
