<?php
/**
 * Separation Degrees One
 *
 * Press release listing and article rendering 
 *
 * @category  SDM
 * @package   SDM_PressReleases
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */

$_listingBlock = $this->getListingBlock();

?>

<h2>
	<?php echo $this->__('Press Releases'); ?>
</h2>

<?php echo $_listingBlock->toHtml(); ?>
