<?php
/**
 * Separation Degrees One
 *
 * Ellison's Teachers' Planning Calendar
 *
 * PHP Version 5
 *
 * @category  SDM
 * @package   SDM_Calendar
 * @author    Separation Degrees One <magento@separationdegrees.com>
 * @copyright Copyright (c) 2015 Separation Degrees One (http://www.separationdegrees.com)
 */
/**
 * @var SDM_Calendar_Block_Calendar $this
 */

$_calendar = $this->getCalendar();
?>
<div class="sdm-calendar-container">
    <h1 class="calendar-name"><?php echo $_calendar->getName() ?></h1>
    <?php echo $this->getEventHtml() ?>
</div>